/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirlines;

import Business.Airline;
import Business.Seat;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sumanth
 */
public class ManageAirlinersWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private TravelAgency travelAgency;
    
    public ManageAirlinersWorkAreaJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        populateJTableForAirline();
    }

    public void populateJTableForAirline() {
        DefaultTableModel dtm = (DefaultTableModel) airlineJTable.getModel();
        dtm.setRowCount(0);
        for (Airline ta : travelAgency.getAirLineDir().getAirlineDir()) {
            Object[] row = new Object[4];
            row[0] = ta;
            row[1] = ta.getAirlinerId();
            row[2] = ta.getAirLineAddr();
            row[3] = ta.getTotalFlightperDay();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createJBtn = new javax.swing.JButton();
        searchAirlineBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        airlineJTable = new javax.swing.JTable();
        searchAirlineTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateAirlinerBtn = new javax.swing.JButton();
        mngflightBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchAirlTable = new javax.swing.JTable();
        deleteAirlineBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createJBtn.setText("Create New Airliners");
        createJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJBtnActionPerformed(evt);
            }
        });
        add(createJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 233, 182, -1));

        searchAirlineBtn.setText("Search Airliners");
        searchAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAirlineBtnActionPerformed(evt);
            }
        });
        add(searchAirlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 346, 135, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Search Airliners Results");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 394, -1, -1));

        airlineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Airline Id", "Airline Address", "Number of Flights per Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(airlineJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 103, 592, 112));
        add(searchAirlineTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 347, 120, -1));

        jLabel2.setText("Airliners");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 350, 53, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Manage Airliners");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 33, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("All Airliners");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 68, 144, -1));

        updateAirlinerBtn.setText("View Airline");
        updateAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirlinerBtnActionPerformed(evt);
            }
        });
        add(updateAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 233, 105, -1));

        mngflightBtn.setText("Select and Manage Flights");
        mngflightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngflightBtnActionPerformed(evt);
            }
        });
        add(mngflightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 612, -1, -1));

        searchAirlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Airline Id", "Airline Address", "Number of Flights per Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(searchAirlTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 441, 597, 133));

        deleteAirlineBtn.setText("Delete Airline");
        deleteAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAirlineBtnActionPerformed(evt);
            }
        });
        add(deleteAirlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 233, 117, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJBtnActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinersJPanel panel = new CreateNewAirlinersJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("CreateNewAirlinersJPanel", panel);
        CardLayout layout1 = (CardLayout) userProcessContainer.getLayout();
        layout1.next(userProcessContainer);

    }//GEN-LAST:event_createJBtnActionPerformed

    private void searchAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAirlineBtnActionPerformed
        String airlinerName = searchAirlineTxtField.getText();
        if (airlinerName.trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please enter Airliner Name");
            return;
        }
        Airline result = travelAgency.getAirLineDir().searchAirline(airlinerName);
        if (result == null) {
            JOptionPane.showMessageDialog(null, "Airliner Name entered is Invalid");
            return;
        } else {
            ArrayList<Airline> airLineValues = new ArrayList();
            ArrayList<Airline> listOfAirlines = travelAgency.getAirLineDir().getAirlineDir();
            int count = 0;
            for (int i = 0; i < listOfAirlines.size(); i++) {
                if (listOfAirlines.get(i).getName().equals(airlinerName)) {
                    airLineValues.add(count, listOfAirlines.get(i));
                    count++;
                }
            }
            populateJTable1(airLineValues);
        }

    }//GEN-LAST:event_searchAirlineBtnActionPerformed

    public void populateJTable1(ArrayList<Airline> populateArrayList) {
        DefaultTableModel tabMod = (DefaultTableModel) searchAirlTable.getModel();
        tabMod.setRowCount(0);
        for (Airline ad : populateArrayList) {
            Object row[] = new Object[4];
            row[0] = ad;
            row[1] = ad.getAirlinerId();
            row[2] = ad.getAirLineAddr();
            row[3] = ad.getTotalFlightperDay();
            tabMod.addRow(row);
        }
    }

    private void mngflightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngflightBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = searchAirlTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select Any Row");
            return;
        } else {
            Airline airline = (Airline) searchAirlTable.getValueAt(selectedRow, 0);
            ManageFlightWorkAreaJPanel panel = new ManageFlightWorkAreaJPanel(userProcessContainer,travelAgency, airline);
            userProcessContainer.add("ManageFlightWorkAreaJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_mngflightBtnActionPerformed

    private void updateAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirlinerBtnActionPerformed
        int selectedRow = airlineJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select Any Row");
            return;
        } else {
            Airline airline = (Airline) airlineJTable.getValueAt(selectedRow, 0);
            UpdateAirlineJPanel panel = new UpdateAirlineJPanel(userProcessContainer, airline);
            userProcessContainer.add("UpdateAirlineJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_updateAirlinerBtnActionPerformed

    private void deleteAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAirlineBtnActionPerformed
        int selectedRow = airlineJTable.getSelectedRow();
        if(selectedRow>=0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the account details", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Airline airline = (Airline) airlineJTable.getValueAt(selectedRow,0);
                travelAgency.getAirLineDir().deleteDetails(airline);
                populateJTableForAirline();
                DefaultTableModel tabMod = (DefaultTableModel) searchAirlTable.getModel();
                tabMod.setRowCount(0);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please Select Any Row","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteAirlineBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlineJTable;
    private javax.swing.JButton createJBtn;
    private javax.swing.JButton deleteAirlineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton mngflightBtn;
    private javax.swing.JTable searchAirlTable;
    private javax.swing.JButton searchAirlineBtn;
    private javax.swing.JTextField searchAirlineTxtField;
    private javax.swing.JButton updateAirlinerBtn;
    // End of variables declaration//GEN-END:variables

}
