/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DistributorRole;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sumanth
 */
public class DistributorEnterQuantityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorEnterQuantity
     */
    JPanel userProcessContainer;
    UserAccount account;
    WorkRequest request;
    Organization org;
    UserAccount currentAccount;

    DistributorEnterQuantityJPanel(JPanel userProcessContainer, UserAccount account, WorkRequest request, Organization org,UserAccount currentAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.request = request;
        this.org = org;
        this.currentAccount = currentAccount;
        avaiQuantTxt.setText(String.valueOf(org.getInventory().getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reqQuantTxt = new javax.swing.JTextField();
        avaiQuantTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        submBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Available Quantity");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 70, 130, 46));
        add(reqQuantTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, -1));

        avaiQuantTxt.setEnabled(false);
        add(avaiQuantTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        jLabel2.setText("Enter Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 109, 46));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        submBtn.setText("Submit");
        submBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submBtnActionPerformed(evt);
            }
        });
        add(submBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DistributorCheckJPanel dwjp = (DistributorCheckJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submBtnActionPerformed
        String value = reqQuantTxt.getText();
        if (value.trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Please enter quantity");
            return;
        }
        try {
            int q = Integer.parseInt(value);
            if (q > org.getInventory().getQuantity()) {
                JOptionPane.showMessageDialog(null, "Please enter Value less than available quantity Values");
                return;
            } else {
                request.getInventory().setQuantity(q);
                org.getInventory().setQuantity(org.getInventory().getQuantity() - q);
                request.setSender(currentAccount);
                request.setReceiver(null);
                request.setStatus("Sent from Distributor to CDC");
                JOptionPane.showMessageDialog(null, "Quantity Sent successfully");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter Integer Values");
            return;
        }
    }//GEN-LAST:event_submBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avaiQuantTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField reqQuantTxt;
    private javax.swing.JButton submBtn;
    // End of variables declaration//GEN-END:variables
}
