/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.LoginScreen.ManageSystemAdmin;

import Business.Business;
import Business.HumanResources.PersonDirectory.Person;
import Business.SystemAdministration.Users;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sumanth
 */
public class UpdateUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateUserJPanel
     */
    JPanel userProcessContainer;
    Business business;
    Person person;
    Users currentUser;
    UpdateUserJPanel(JPanel userProcessContainer, Business business, Person person,Users currentUser) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.person=person;
        this.currentUser = currentUser;
        setAllValues();
    }
    
    public void setAllValues(){
        String status = person.getUser().getAccountStatus();
        if(status.equals("Active")){
            activeBtn.setSelected(true);
        }else if(status.equals("Disabled")){
            disabledBtn.setSelected(true);
        }
        personTxt.setText(person.toString());
        userNameTxt.setText(person.getUser().getUserName());
        passwordTxt.setText(person.getUser().getPassword());
        roleTxt.setText(person.getUser().getRole());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        personTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateUserBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        roleTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        activeBtn = new javax.swing.JRadioButton();
        disabledBtn = new javax.swing.JRadioButton();
        userNameTxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Select Person");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, 40));

        jLabel4.setText("UserName:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, 40));

        personTxt.setEnabled(false);
        add(personTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 140, 40));

        jLabel6.setText("Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 110, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("                            Update User Account Directory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 410, 60));

        jLabel2.setText("Role");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 120, 40));

        updateUserBtn.setText("Update");
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });
        add(updateUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 80, 30));

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        roleTxt.setEnabled(false);
        add(roleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 140, 40));

        passwordTxt.setEnabled(false);
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 140, 40));

        jLabel5.setText("Account Status");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 160, 40));

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 70, 30));

        buttonGroup1.add(activeBtn);
        activeBtn.setText("Active");
        activeBtn.setEnabled(false);
        add(activeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        buttonGroup1.add(disabledBtn);
        disabledBtn.setText("Disabled");
        disabledBtn.setEnabled(false);
        add(disabledBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        userNameTxt.setEnabled(false);
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
        activeBtn.setEnabled(true);
        disabledBtn.setEnabled(true);
        saveBtn.setEnabled(true);
        updateUserBtn.setEnabled(false);
    }//GEN-LAST:event_updateUserBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageSystemAdminJPanel panel = (ManageSystemAdminJPanel) component;
        panel.populateJTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        activeBtn.setEnabled(false);
        disabledBtn.setEnabled(false);
        saveBtn.setEnabled(false);
        updateUserBtn.setEnabled(true);
        if(currentUser.getUserName().equals(person.getUser().getUserName())){
            activeBtn.setSelected(true);
            JOptionPane.showMessageDialog(null, "User cannot disable his own account");
            return;
        }
        if(activeBtn.isSelected()){
            person.getUser().setAccountStatus("Active");
        }else if(disabledBtn.isSelected()){
            person.getUser().setAccountStatus("Disabled");
        }
        JOptionPane.showMessageDialog(null, "User Account Updated Successfully");
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton disabledBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField personTxt;
    private javax.swing.JTextField roleTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateUserBtn;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
