/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AirplaneDetails;
import Business.AirplaneDetailsHistory;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Sumanth
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */ 
    
    private AirplaneDetailsHistory airplaneDetailsHist;
    CreateJPanel(AirplaneDetailsHistory airplaneDetailsHist) {
        initComponents();
        this.airplaneDetailsHist = airplaneDetailsHist;
        if(createPlaneDet.getSelectedItem().equals("From File")){
            jPanelFromData.setVisible(false);
            jPanelFromFile.setVisible(true);
        }else if(createPlaneDet.getSelectedItem().equals("From List of Data")){
           jPanelFromData.setVisible(true);
            jPanelFromFile.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createPlaneDet = new javax.swing.JComboBox<>();
        saveJBtn = new javax.swing.JButton();
        jPanelFromData = new javax.swing.JPanel();
        yearOfManLabel = new javax.swing.JLabel();
        numOfSeatsLabel = new javax.swing.JLabel();
        serNoLabel = new javax.swing.JLabel();
        modelNoLabel = new javax.swing.JLabel();
        timeOfFleetCatLabel = new javax.swing.JLabel();
        maintCertExpLabel = new javax.swing.JLabel();
        availablityLabel = new javax.swing.JLabel();
        airportNameLabel = new javax.swing.JLabel();
        airplaneNameTxt = new javax.swing.JTextField();
        yearOfManTxt = new javax.swing.JTextField();
        numOfSeatsTxt = new javax.swing.JTextField();
        serNoTxt = new javax.swing.JTextField();
        modelNoTxt = new javax.swing.JTextField();
        airplaneNameLabel = new javax.swing.JLabel();
        timeOfFleetCatTxt = new javax.swing.JTextField();
        airportNameTxt = new javax.swing.JTextField();
        maintCertExpChkBox = new javax.swing.JCheckBox();
        availablityChkBox = new javax.swing.JCheckBox();
        airportNameLabel1 = new javax.swing.JLabel();
        manuNameTxt = new javax.swing.JTextField();
        airportNameLabel2 = new javax.swing.JLabel();
        dateOfFlyTxt = new javax.swing.JTextField();
        jPanelFromFile = new javax.swing.JPanel();
        csvLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create Airplane Details");

        jLabel2.setText("Select way to create Airplane Details");

        createPlaneDet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "From File", "From List of Data" }));
        createPlaneDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaneDetActionPerformed(evt);
            }
        });

        saveJBtn.setText("Save");
        saveJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJBtnActionPerformed(evt);
            }
        });

        yearOfManLabel.setText("  Year of Manufacture: ");

        numOfSeatsLabel.setText("Number of Seats:");

        serNoLabel.setText("Serail Number:");

        modelNoLabel.setText("Model Number:");

        timeOfFleetCatLabel.setText("Fleet Catalog updated Date:");

        maintCertExpLabel.setText("Maintainance Certficate Expired:");

        availablityLabel.setText("Availablity of Airplane:");

        airportNameLabel.setText("Airport Name:");

        airplaneNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplaneNameTxtActionPerformed(evt);
            }
        });

        airplaneNameLabel.setText("Airplane Name:");

        availablityChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablityChkBoxActionPerformed(evt);
            }
        });

        airportNameLabel1.setText("Manufacturer Name:");

        airportNameLabel2.setText("Date of Departure:");

        javax.swing.GroupLayout jPanelFromDataLayout = new javax.swing.GroupLayout(jPanelFromData);
        jPanelFromData.setLayout(jPanelFromDataLayout);
        jPanelFromDataLayout.setHorizontalGroup(
            jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFromDataLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(airplaneNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numOfSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airportNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelFromDataLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(availablityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(timeOfFleetCatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maintCertExpLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(airportNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearOfManLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airportNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateOfFlyTxt)
                    .addComponent(manuNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serNoTxt)
                    .addComponent(modelNoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeOfFleetCatTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airportNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearOfManTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numOfSeatsTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFromDataLayout.createSequentialGroup()
                        .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maintCertExpChkBox)
                            .addComponent(availablityChkBox)
                            .addComponent(airplaneNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
        );
        jPanelFromDataLayout.setVerticalGroup(
            jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFromDataLayout.createSequentialGroup()
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplaneNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airplaneNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearOfManLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearOfManTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numOfSeatsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeOfFleetCatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeOfFleetCatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maintCertExpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintCertExpChkBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availablityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availablityChkBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airportNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airportNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manuNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airportNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFromDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfFlyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airportNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        csvLabel.setText("Please select save inorder to create data from csv file");

        javax.swing.GroupLayout jPanelFromFileLayout = new javax.swing.GroupLayout(jPanelFromFile);
        jPanelFromFile.setLayout(jPanelFromFileLayout);
        jPanelFromFileLayout.setHorizontalGroup(
            jPanelFromFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFromFileLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(csvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanelFromFileLayout.setVerticalGroup(
            jPanelFromFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(csvLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createPlaneDet, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanelFromData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanelFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(saveJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(createPlaneDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanelFromFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFromData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveJBtn)
                .addGap(326, 326, 326))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void createPlaneDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaneDetActionPerformed
        JTextField[] textDet ={airplaneNameTxt,yearOfManTxt,numOfSeatsTxt,serNoTxt,modelNoTxt,timeOfFleetCatTxt,airportNameTxt,manuNameTxt,dateOfFlyTxt};
        if(createPlaneDet.getSelectedItem().equals("From File")){
            jPanelFromData.setVisible(false);
            jPanelFromFile.setVisible(true);
        }else if(createPlaneDet.getSelectedItem().equals("From List of Data")){
            clearTextValues(textDet);
           jPanelFromData.setVisible(true);
            jPanelFromFile.setVisible(false);
        }
    }//GEN-LAST:event_createPlaneDetActionPerformed

    public void clearTextValues(JTextField[] textDet){
        for(JTextField td:textDet){
                td.setText("");
            }
    }
    private void airplaneNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplaneNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplaneNameTxtActionPerformed

    private void saveJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJBtnActionPerformed
       SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        if(createPlaneDet.getSelectedItem().equals("From File")){
           String[] pp1= {"setAirplaneName","setDateOfFly"};
           String[] pp2= {"airplaneNameTxt.getText()","formatter.parse(dateOfFlyTxt.getText())"};
           String csvFile = "AirplaneDetails.csv";
	        BufferedReader bufferedReader = null;
	        String line = "";
	        String cvsSplitBy = ",";
	        try {
	            bufferedReader = new BufferedReader(new FileReader(csvFile));
                    ArrayList<String[]> dataCsvArr = new ArrayList();
                    int count = 0;
	            while ((line = bufferedReader.readLine()) != null) {
	                String[] dataFromCsv = line.split(cvsSplitBy);
                        dataCsvArr.add(count,dataFromCsv);
                        count++;
	            }
                    for(int i=1;i<dataCsvArr.size();i++){
                        AirplaneDetails airDet = airplaneDetailsHist.addDetails();
                        String valuesOfArray[] = dataCsvArr.get(i);
                        airDet.setAirplaneName(valuesOfArray[0]);
                        try {
                            airDet.setDateOfFly(formatter.parse(valuesOfArray[1]));
                            airDet.setTimeOfFleetCat(formatter.parse(valuesOfArray[6]));
                        } catch (ParseException ex) {
                             Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
                         }
                        airDet.setYearOfMan(Integer.parseInt(valuesOfArray[2]));
                        airDet.setNumOfSeats(Integer.parseInt(valuesOfArray[3]));
                        airDet.setSerNo(Double.parseDouble(valuesOfArray[4]));
                        airDet.setModelNo(Double.parseDouble(valuesOfArray[5]));
                        airDet.setMaintCertExp(valuesOfArray[7]); 
                        airDet.setAvailablity(valuesOfArray[8]);
                        airDet.setAirportName(valuesOfArray[9]);
                        airDet.setManuName(valuesOfArray[10]);
                    }
	            bufferedReader.close();
	        } catch (FileNotFoundException e) {
	            e.printStackTrace();
	  } catch (IOException ex) {
               Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
       }else if(createPlaneDet.getSelectedItem().equals("From List of Data")){
           AirplaneDetails airDet = airplaneDetailsHist.addDetails();
           airDet.setAirplaneName(airplaneNameTxt.getText());
           try {
               airDet.setDateOfFly(formatter.parse(dateOfFlyTxt.getText()));
               airDet.setTimeOfFleetCat(formatter.parse(timeOfFleetCatTxt.getText()));
           } catch (ParseException ex) {
               Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
           airDet.setYearOfMan(Integer.parseInt(yearOfManTxt.getText()));
           airDet.setNumOfSeats(Integer.parseInt(numOfSeatsTxt.getText()));
           airDet.setSerNo(Double.parseDouble(serNoTxt.getText()));
           airDet.setModelNo(Double.parseDouble(modelNoTxt.getText()));
           if(maintCertExpChkBox.isSelected()){
              airDet.setMaintCertExp("Yes"); 
           }else{
               airDet.setMaintCertExp("No"); 
           }
           if(availablityChkBox.isSelected()){
               airDet.setAvailablity("Yes");
           }else{
               airDet.setAvailablity("No");
           }
           airDet.setAirportName(airportNameTxt.getText());
           airDet.setManuName(manuNameTxt.getText());
       }
    }//GEN-LAST:event_saveJBtnActionPerformed

    private void availablityChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablityChkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availablityChkBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airplaneNameLabel;
    private javax.swing.JLabel airplaneNameLabel2;
    private javax.swing.JTextField airplaneNameTxt;
    private javax.swing.JTextField airplaneNameTxt2;
    private javax.swing.JLabel airportNameLabel;
    private javax.swing.JLabel airportNameLabel1;
    private javax.swing.JLabel airportNameLabel2;
    private javax.swing.JLabel airportNameLabel6;
    private javax.swing.JLabel airportNameLabel7;
    private javax.swing.JLabel airportNameLabel8;
    private javax.swing.JTextField airportNameTxt;
    private javax.swing.JTextField airportNameTxt2;
    private javax.swing.JCheckBox availablityChkBox;
    private javax.swing.JCheckBox availablityChkBox2;
    private javax.swing.JLabel availablityLabel;
    private javax.swing.JLabel availablityLabel2;
    private javax.swing.JComboBox<String> createPlaneDet;
    private javax.swing.JLabel csvLabel;
    private javax.swing.JTextField dateOfFlyTxt;
    private javax.swing.JTextField dateOfFlyTxt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelFromData;
    private javax.swing.JPanel jPanelFromData2;
    private javax.swing.JPanel jPanelFromFile;
    private javax.swing.JCheckBox maintCertExpChkBox;
    private javax.swing.JCheckBox maintCertExpChkBox2;
    private javax.swing.JLabel maintCertExpLabel;
    private javax.swing.JLabel maintCertExpLabel2;
    private javax.swing.JTextField manuNameTxt;
    private javax.swing.JTextField manuNameTxt2;
    private javax.swing.JLabel modelNoLabel;
    private javax.swing.JLabel modelNoLabel2;
    private javax.swing.JTextField modelNoTxt;
    private javax.swing.JTextField modelNoTxt2;
    private javax.swing.JLabel numOfSeatsLabel;
    private javax.swing.JLabel numOfSeatsLabel2;
    private javax.swing.JTextField numOfSeatsTxt;
    private javax.swing.JTextField numOfSeatsTxt2;
    private javax.swing.JButton saveJBtn;
    private javax.swing.JLabel serNoLabel;
    private javax.swing.JLabel serNoLabel2;
    private javax.swing.JTextField serNoTxt;
    private javax.swing.JTextField serNoTxt2;
    private javax.swing.JLabel timeOfFleetCatLabel;
    private javax.swing.JLabel timeOfFleetCatLabel2;
    private javax.swing.JTextField timeOfFleetCatTxt;
    private javax.swing.JTextField timeOfFleetCatTxt2;
    private javax.swing.JLabel yearOfManLabel;
    private javax.swing.JLabel yearOfManLabel2;
    private javax.swing.JTextField yearOfManTxt;
    private javax.swing.JTextField yearOfManTxt2;
    // End of variables declaration//GEN-END:variables
}
