/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AirplaneDetails;
import Business.AirplaneDetailsHistory;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sumanth
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private AirplaneDetailsHistory airplaneDetailsHist;
    public ViewJPanel(AirplaneDetailsHistory airplaneDetailsHist) {
        initComponents();
        this.airplaneDetailsHist = airplaneDetailsHist;
        populateJTable();
        searchPanel.setVisible(true);
        searchLabel.setText("");
        searchTxtField.setText("");
        searchChkBox.setVisible(false);
        JScrollPane sp = new JScrollPane();
        this.add(sp);
    }
    
    public void populateJTable(){
        DefaultTableModel tabMod = (DefaultTableModel) airDetTable.getModel();
        tabMod.setRowCount(0);
        for(AirplaneDetails ad:  airplaneDetailsHist.getAirDetHist()){
            Object row[] = new Object[3];
            row[0] = ad;
            row[1] = ad.getYearOfMan();
            row[2] = ad.getSerNo();
            tabMod.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airDetTable = new javax.swing.JTable();
        viewAirDetJBtn = new javax.swing.JButton();
        yearOfManLabel3 = new javax.swing.JLabel();
        numOfSeatsLabel3 = new javax.swing.JLabel();
        serNoLabel3 = new javax.swing.JLabel();
        modelNoLabel3 = new javax.swing.JLabel();
        timeOfFleetCatLabel3 = new javax.swing.JLabel();
        maintCertExpLabel3 = new javax.swing.JLabel();
        availablityLabel3 = new javax.swing.JLabel();
        airportNameLabel9 = new javax.swing.JLabel();
        airplaneNameTxt3 = new javax.swing.JTextField();
        yearOfManTxt3 = new javax.swing.JTextField();
        numOfSeatsTxt3 = new javax.swing.JTextField();
        serNoTxt3 = new javax.swing.JTextField();
        modelNoTxt3 = new javax.swing.JTextField();
        airplaneNameLabel3 = new javax.swing.JLabel();
        timeOfFleetCatTxt3 = new javax.swing.JTextField();
        airportNameTxt3 = new javax.swing.JTextField();
        maintCertExpChkBox3 = new javax.swing.JCheckBox();
        availablityChkBox3 = new javax.swing.JCheckBox();
        airportNameLabel10 = new javax.swing.JLabel();
        manuNameTxt3 = new javax.swing.JTextField();
        airportNameLabel11 = new javax.swing.JLabel();
        dateOfFlyTxt3 = new javax.swing.JTextField();
        searchListBox = new javax.swing.JComboBox<>();
        serachBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchJTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchJTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchTxtField = new javax.swing.JTextField();
        searchChkBox = new javax.swing.JCheckBox();
        searchLabDest = new javax.swing.JLabel();
        searchTxtDest = new javax.swing.JTextField();
        airportNameLabel13 = new javax.swing.JLabel();
        originTxt = new javax.swing.JTextField();
        originTxt1 = new javax.swing.JTextField();
        airportNameLabel14 = new javax.swing.JLabel();
        destinationTxt = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Airplane Details");

        airDetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name", "Year of Manufacture", "Serial Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airDetTable);

        viewAirDetJBtn.setText("View");
        viewAirDetJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirDetJBtnActionPerformed(evt);
            }
        });

        yearOfManLabel3.setText("  Year of Manufacture: ");

        numOfSeatsLabel3.setText("Number of Seats:");

        serNoLabel3.setText("Serail Number:");

        modelNoLabel3.setText("Model Number:");

        timeOfFleetCatLabel3.setText("Fleet Catalog updated Date:");

        maintCertExpLabel3.setText("Maintainance Certficate Expired:");

        availablityLabel3.setText("Availablity of Airplane:");

        airportNameLabel9.setText("Airport Name:");

        airplaneNameTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplaneNameTxt3ActionPerformed(evt);
            }
        });

        airplaneNameLabel3.setText("Airplane Name:");

        availablityChkBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablityChkBox3ActionPerformed(evt);
            }
        });

        airportNameLabel10.setText("Manufacturer Name:");

        airportNameLabel11.setText("Date of Departure:");

        searchListBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Available Airplane", "Currently Available Airplanes", "Airplanes made of Boeing", "Manufactured year", "Number of seats Available", "Serial Number", "Model Number", "Manufacturer Name", "Fleet Catalog updated date", "Airport Name", "Maintainance Cerificate Expired" }));
        searchListBox.setToolTipText("");
        searchListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchListBoxActionPerformed(evt);
            }
        });

        serachBtn.setText("Search");
        serachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachBtnActionPerformed(evt);
            }
        });

        searchJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name", "Date of Departure", "Serial Number", "Year of Manufacture", "Number of Seats", "Model Number", "Fleet Catalog updated Date", "Maintainance Certificate Expired", "Availablity of Airplane", "Airport Name", "Manufacturer Name", "Origin", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(searchJTable);

        searchJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name", "Date of Departure", "Serial Number", "Year of Manufacture", "Number of Seats", "Model Number", "Fleet Catalog updated Date", "Maintainance Certificate Expired", "Availablity of Airplane", "Airport Name", "Manufacturer Name", "Origin", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(searchJTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search Based on Criteria ");

        searchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFieldActionPerformed(evt);
            }
        });

        searchChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchChkBoxActionPerformed(evt);
            }
        });

        searchTxtDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtDestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchLabDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchChkBox)
                .addGap(12, 12, 12)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTxtDest)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchChkBox)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchTxtDest, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        airportNameLabel13.setText("             Origin");

        airportNameLabel14.setText("          Destination");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(airportNameLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(viewAirDetJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(230, 230, 230)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(118, 118, 118)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(128, 128, 128)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(airplaneNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(numOfSeatsLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(serNoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(modelNoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(yearOfManLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(32, 32, 32))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(airportNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(modelNoTxt3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(serNoTxt3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numOfSeatsTxt3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yearOfManTxt3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(airplaneNameTxt3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateOfFlyTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(availablityLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(timeOfFleetCatLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(maintCertExpLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(airportNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(airportNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(airportNameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(maintCertExpChkBox3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(availablityChkBox3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(airportNameTxt3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timeOfFleetCatTxt3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                        .addComponent(manuNameTxt3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(originTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewAirDetJBtn)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airplaneNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airplaneNameTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearOfManLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearOfManTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOfSeatsLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfSeatsTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serNoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serNoTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelNoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelNoTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfFlyTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportNameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeOfFleetCatLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeOfFleetCatTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maintCertExpLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maintCertExpChkBox3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availablityLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availablityChkBox3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airportNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportNameTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manuNameTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(originTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(airportNameLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(serachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(searchListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewAirDetJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirDetJBtnActionPerformed
        int selectedRow  = airDetTable.getSelectedRow();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        if(selectedRow>=0){
            AirplaneDetails airDet = (AirplaneDetails) airDetTable.getValueAt(selectedRow, 0);
             airplaneNameTxt3.setText(airDet.getAirplaneName());
           try {
               dateOfFlyTxt3.setText(formatter.format(airDet.getDateOfFly()));
               timeOfFleetCatTxt3.setText(formatter.format(airDet.getTimeOfFleetCat()));
           } catch (Exception ex) {
               Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
           yearOfManTxt3.setText(String.valueOf(airDet.getYearOfMan()));
           numOfSeatsTxt3.setText(String.valueOf(airDet.getNumOfSeats()));
           serNoTxt3.setText(String.valueOf(airDet.getSerNo()));
           modelNoTxt3.setText(String.valueOf(airDet.getModelNo()));
           if(airDet.getMaintCertExp().equals("Yes")){
               maintCertExpChkBox3.setSelected(true);
           }
           if(airDet.getAvailablity().equals("Yes")){
               availablityChkBox3.setSelected(true);
           }
           airportNameTxt3.setText(airDet.getAirportName());
           manuNameTxt3.setText(airDet.getManuName());
           originTxt.setText(airDet.getOrigin());
           destinationTxt.setText(airDet.getDestination());
        }else{
            JOptionPane.showMessageDialog(null, "Please Select any Row");
        }
    }//GEN-LAST:event_viewAirDetJBtnActionPerformed

    private void airplaneNameTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplaneNameTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplaneNameTxt3ActionPerformed

    private void availablityChkBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablityChkBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availablityChkBox3ActionPerformed

    private void serachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachBtnActionPerformed
        ArrayList<AirplaneDetails> modArrList= new ArrayList();
        ArrayList<AirplaneDetails> airDetForSearch = airplaneDetailsHist.getAirDetHist();
        int count = 0;
        if(searchListBox.getSelectedItem().equals("First Available Airplane")){
            List<Date> dateValues = new ArrayList();
            String originValue = searchTxtField.getText();
            String destinationValue = searchTxtDest.getText();
           for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getOrigin().equals(originValue) && eachSearchValue.getDestination().equals(destinationValue)){
                   dateValues.add(eachSearchValue.getDateOfFly());
               }
           }
           Collections.sort(dateValues);
           for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getDateOfFly()== dateValues.get(0)){
                  modArrList.add(count, eachSearchValue);
                  break;
               }
           }
        }else if(searchListBox.getSelectedItem().equals("Currently Available Airplanes")){
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getAvailablity().equals("Yes")){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }else if(searchListBox.getSelectedItem().equals("Manufactured year")){
            String yearValue = searchTxtField.getText();
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getYearOfMan() == (Integer.parseInt(yearValue))){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }else if(searchListBox.getSelectedItem().equals("Number of seats Available")){
            
        }else if(searchListBox.getSelectedItem().equals("Serial Number")){
            String serNoValue = searchTxtField.getText();
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getSerNo().equals(serNoValue)){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }else if(searchListBox.getSelectedItem().equals("Model Number")){
            String modelNoValue = searchTxtField.getText();
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getModelNo().equals(modelNoValue)){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }else if(searchListBox.getSelectedItem().equals("Manufacturer Name")){
            String manuNamValue = searchTxtField.getText();
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getManuName().equals(manuNamValue)){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }else if(searchListBox.getSelectedItem().equals("Fleet Catalog updated date")){
            
        }else if(searchListBox.getSelectedItem().equals("Airport Name")){
            String airNamValue = searchTxtField.getText();
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getAirportName().equals(airNamValue)){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }else if(searchListBox.getSelectedItem().equals("Maintainance Cerificate Expired")){
            String maintCertValue ;
            if(searchChkBox.isSelected()){
                maintCertValue = "Yes";
            }else{
                maintCertValue = "No";
            }
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getMaintCertExp().equals(maintCertValue)){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }else if(searchListBox.getSelectedItem().equals("Airplanes made of Boeing")){
            for(AirplaneDetails eachSearchValue: airDetForSearch){
               if(eachSearchValue.getAirplaneName().equals("Boeing")){
                   modArrList.add(count, eachSearchValue);
                   count++;
               }
            }
        }
        populateJTable1(modArrList);
    }//GEN-LAST:event_serachBtnActionPerformed

    private void searchListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchListBoxActionPerformed
        if(searchListBox.getSelectedItem().equals("First Available Airplane")){
            searchPanel.setVisible(false);
            searchLabel.setText("");
            searchTxtField.setText("");
        }else if(searchListBox.getSelectedItem().equals("Currently Available Airplanes")){
            searchPanel.setVisible(false);
            searchLabel.setText("");
            searchTxtField.setText("");
        }else if(searchListBox.getSelectedItem().equals("Manufactured year")){
            searchPanel.setVisible(true);
            searchLabel.setVisible(true);
            searchTxtField.setVisible(true);
            searchLabel.setText("Year");
            searchTxtField.setText("");
            searchChkBox.setVisible(false);
        }else if(searchListBox.getSelectedItem().equals("Number of seats Available")){
            
        }else if(searchListBox.getSelectedItem().equals("Serial Number")){
            searchPanel.setVisible(true);
            searchLabel.setVisible(true);
            searchTxtField.setVisible(true);
            searchLabel.setText("Enter Number");
            searchTxtField.setText("");
            searchChkBox.setVisible(false);
        }else if(searchListBox.getSelectedItem().equals("Model Number")){
            searchPanel.setVisible(true);
            searchLabel.setVisible(true);
            searchTxtField.setVisible(true);
            searchLabel.setText("Enter Number");
            searchTxtField.setText("");
            searchChkBox.setVisible(false);
        }else if(searchListBox.getSelectedItem().equals("Manufacturer Name")){
            searchPanel.setVisible(true);
            searchLabel.setVisible(true);
            searchTxtField.setVisible(true);
            searchLabel.setText("Enter Name");
            searchTxtField.setText("");
            searchChkBox.setVisible(false);
        }else if(searchListBox.getSelectedItem().equals("Fleet Catalog updated date")){
            
        }else if(searchListBox.getSelectedItem().equals("Airport Name")){
            searchPanel.setVisible(true);
            searchLabel.setVisible(true);
            searchTxtField.setVisible(true);
            searchLabel.setText("Enter Name");
            searchTxtField.setText("");
            searchChkBox.setVisible(false);
        }else if(searchListBox.getSelectedItem().equals("Maintainance Cerificate Expired")){
            searchPanel.setVisible(true);
            searchLabel.setVisible(false);
            searchTxtField.setVisible(false);
            searchChkBox.setVisible(true);
        }else if(searchListBox.getSelectedItem().equals("Airplanes made of Boeing")){
            searchPanel.setVisible(false);
            searchLabel.setText("");
            searchTxtField.setText("");
        }
    }//GEN-LAST:event_searchListBoxActionPerformed

    private void searchChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchChkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchChkBoxActionPerformed

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    private void searchTxtDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtDestActionPerformed

    public void populateJTable1(ArrayList<AirplaneDetails> modArrList){
        DefaultTableModel tabMod = (DefaultTableModel) searchJTable.getModel();
        tabMod.setRowCount(0);
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        for(AirplaneDetails ad:  modArrList){
            Object row[] = new Object[11];
            row[0] = ad;
            row[1] = formatter.format(ad.getDateOfFly());
            row[2] = ad.getSerNo();
            row[3] = ad.getYearOfMan();
            row[4] = ad.getNumOfSeats();
            row[5] = ad.getModelNo();
            row[6] = formatter.format(ad.getTimeOfFleetCat());
            row[7] = ad.getMaintCertExp();
            row[8] = ad.getAvailablity();
            row[9] = ad.getAirportName();
            row[10] = ad.getManuName();
            tabMod.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airDetTable;
    private javax.swing.JLabel airplaneNameLabel3;
    private javax.swing.JTextField airplaneNameTxt3;
    private javax.swing.JLabel airportNameLabel10;
    private javax.swing.JLabel airportNameLabel11;
    private javax.swing.JLabel airportNameLabel13;
    private javax.swing.JLabel airportNameLabel14;
    private javax.swing.JLabel airportNameLabel9;
    private javax.swing.JTextField airportNameTxt3;
    private javax.swing.JCheckBox availablityChkBox3;
    private javax.swing.JLabel availablityLabel3;
    private javax.swing.JTextField dateOfFlyTxt3;
    private javax.swing.JTextField destinationTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JCheckBox maintCertExpChkBox3;
    private javax.swing.JLabel maintCertExpLabel3;
    private javax.swing.JTextField manuNameTxt3;
    private javax.swing.JLabel modelNoLabel3;
    private javax.swing.JTextField modelNoTxt3;
    private javax.swing.JLabel numOfSeatsLabel3;
    private javax.swing.JTextField numOfSeatsTxt3;
    private javax.swing.JTextField originTxt;
    private javax.swing.JTextField originTxt1;
    private javax.swing.JCheckBox searchChkBox;
    private javax.swing.JTable searchJTable;
    private javax.swing.JTable searchJTable1;
    private javax.swing.JLabel searchLabDest;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JComboBox<String> searchListBox;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTxtDest;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JLabel serNoLabel3;
    private javax.swing.JTextField serNoTxt3;
    private javax.swing.JButton serachBtn;
    private javax.swing.JLabel timeOfFleetCatLabel3;
    private javax.swing.JTextField timeOfFleetCatTxt3;
    private javax.swing.JButton viewAirDetJBtn;
    private javax.swing.JLabel yearOfManLabel3;
    private javax.swing.JTextField yearOfManTxt3;
    // End of variables declaration//GEN-END:variables
}
