/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClinicRole;

import Business.Organization.Organization;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sumanth
 */
public class ClinicSetQuantityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicSetQuantityJPanel
     */
    JPanel userProcessContainer;
    WorkRequest req;
    Organization clinicOrganization;
    ClinicSetQuantityJPanel(JPanel userProcessContainer, Organization clinicOrganization, WorkRequest req) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.req = req;
        this.clinicOrganization = clinicOrganization;
        availTxt.setText(String.valueOf(req.getInventory().getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        availTxt = new javax.swing.JTextField();
        reqTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Distribute Vaccine");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 25, 250, 40));

        jLabel2.setText("Available Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 110, 110, 30));

        jLabel3.setText("Required Quantity");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));

        availTxt.setEnabled(false);
        add(availTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, 30));
        add(reqTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 120, 30));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 90, 40));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String value = reqTxt.getText();
        if (value.trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Please enter quantity");
            return;
        }
        try {
            int q = Integer.parseInt(value);
            if(q>req.getInventory().getQuantity()){
                JOptionPane.showMessageDialog(null, "Please enter quantity less than available Value");
                return;
            }
                req.getInventory().setQuantity(req.getInventory().getQuantity()-q);
                availTxt.setText(String.valueOf(req.getInventory().getQuantity()));
                JOptionPane.showMessageDialog(null, "Quantity Sent successfully");
                reqTxt.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter Integer Values");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClinicInventoryJPanel dwjp = (ClinicInventoryJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField reqTxt;
    // End of variables declaration//GEN-END:variables
}
