/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdminLogin.Revenue;

import Business.Business;
import Business.Market;
import Business.Order;
import Business.OrderList;
import Business.Product;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sumanth
 */
public class ProductSalesRevenueJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductSalesRevenueJPanel
     */
    JPanel userProcessContainer;
    Business business;
    public ProductSalesRevenueJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business =business;
        salesRevenue();
    }
    
    public void salesRevenue(){
        ArrayList<OrderList> listOfOrders = business.getMasterOrderCatalog().getOrderList();
        List <String> allMarkets = new ArrayList();
        for(OrderList ol:listOfOrders){
            for(Order o:ol.getOrderList()){
                allMarkets.add(o.getMarket().getMarketName());
            }
        }
        allMarkets = allMarkets.stream().distinct().collect(Collectors.toList());
        marketNameBox.removeAllItems();
        for (String s : allMarkets) {
            marketNameBox.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marketNameBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodJTable = new javax.swing.JTable();
        revenueTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        targPriceTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        actPriceTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gapPriceTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        profitTxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(marketNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 230, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("       Product sales revenues by market");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 310, 50));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, -1, -1));

        prodJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prodJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 290, 120));

        revenueTxt.setEnabled(false);
        add(revenueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 120, 30));

        jLabel2.setText("Revenue of the market :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 30));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 130, 40));

        jLabel3.setText("Market Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 124, 110, 40));

        targPriceTxt.setEnabled(false);
        targPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targPriceTxtActionPerformed(evt);
            }
        });
        add(targPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 140, 40));

        jLabel4.setText("Target Price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 100, 40));

        actPriceTxt.setEnabled(false);
        actPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actPriceTxtActionPerformed(evt);
            }
        });
        add(actPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 140, 40));

        jLabel5.setText("Actual Price");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 100, 40));

        gapPriceTxt.setEnabled(false);
        gapPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gapPriceTxtActionPerformed(evt);
            }
        });
        add(gapPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 140, 40));

        jLabel6.setText("Gap Price between Target and Actual");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 230, 40));

        jLabel7.setText("Missed Revenue/Profit");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 230, 40));

        profitTxt.setEnabled(false);
        profitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitTxtActionPerformed(evt);
            }
        });
        add(profitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String marketName = (String)marketNameBox.getSelectedItem();
        ArrayList<OrderList> listOfOrders = business.getMasterOrderCatalog().getOrderList();
        ArrayList<Product> prodList = new ArrayList();
        double price = 0;
        double actualPrice=0;
        double targetPrice=0;
        for(OrderList ol:listOfOrders){
            for(Order o:ol.getOrderList()){
                if(o.getMarket().getMarketName().equals(marketName)){
                    prodList.add(o.getProduct());
                    price = price +(o.getQuantity()*o.getSalesPrice());
                    actualPrice = actualPrice + ((o.getProduct().getPrice()) * o.getQuantity());
                    targetPrice = targetPrice + ((o.getProduct().getPrice()*1.2) * o.getQuantity());
                }
            }
        }
        revenueTxt.setText(String.valueOf(price));
        double gapPrice = targetPrice - actualPrice;
        actPriceTxt.setText(String.valueOf(actualPrice));
        targPriceTxt.setText(String.valueOf(targetPrice));
        gapPriceTxt.setText(String.valueOf(gapPrice));
        profitTxt.setText(String.valueOf(price-targetPrice));
        DefaultTableModel model = (DefaultTableModel) prodJTable.getModel();
        model.setRowCount(0);
        for (Product p : prodList) {
            Object row[] = new Object[1];
            row[0] = p;
            model.addRow(row);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void targPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targPriceTxtActionPerformed

    private void actPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actPriceTxtActionPerformed

    private void gapPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gapPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gapPriceTxtActionPerformed

    private void profitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actPriceTxt;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField gapPriceTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox marketNameBox;
    private javax.swing.JTable prodJTable;
    private javax.swing.JTextField profitTxt;
    private javax.swing.JTextField revenueTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField targPriceTxt;
    // End of variables declaration//GEN-END:variables
}
